name: Build and Publish Nightly

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - ".vscode/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'workflow_dispatch'
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: mr-smithers-excellent/docker-build-push@v6
        if: github.event_name != 'workflow_dispatch'
        with:
          image: ui
          tags: nightly,${{ github.sha }}
          registry: ghcr.io
          directory: ./
          dockerfile: ./Dockerfile
          addLatest: false
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate static files
        run: pnpm generate

      - name: Upload client bundle
        uses: actions/upload-artifact@v4
        with:
          name: client-bundle
          path: |
            .output/public

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download client bundle
        uses: actions/download-artifact@v4
        with:
          name: client-bundle
          path: .output/public

      - name: Updating config.json for not-th.re public
        run: >
          echo "{\"baseURL\": \"https://api.not-th.re/\", \"termsURL\":
          \"https://scolasti.co/go/privacy\"}" > .output/public/config.json

      - name: Upload client bundle to cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .output/public/ --project-name=not-three --commit-dirty=true --branch=main
          packageManager: npm
